Corrections

diff --git a/0x08-networking_basics_2/1-show_attached_IPs b/0x08-networking_basics_2/1-show_attached_IPs
--- a/0x08-networking_basics_2/1-show_attached_IPs
+++ b/0x08-networking_basics_2/1-show_attached_IPs
@@ -1,9 +1,10 @@
 #!/bin/bash
 
 # This script displays all active IPv4 addre
-if ! command -v ifconfig &> /dev/null; then
-    echo "Error: ifconfig command not found. Make sure the net-tools package is installed."
-    exit 1
-fi
+# if ! command -v ifconfig &> /dev/null; then
+#    echo "Error: ifconfig command not found. Make sure the net-tools package is installed."
+#    exit 1
+# fi
 
 ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6-
+
